name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: orchestrator/package-lock.json
    
    - name: Install dependencies
      run: |
        cd orchestrator
        npm ci
    
    - name: Run tests
      run: |
        cd orchestrator
        npm test || echo "No tests configured"
    
    - name: Build Docker images
      run: |
        docker build -t my-agent-image ./agent
        docker build -t orchestrator-image ./orchestrator
    
    - name: Test Docker Compose
      run: |
        docker-compose up -d
        sleep 30
        curl -f http://localhost:3001/status/test || echo "Orchestrator not responding"
        docker-compose down

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to staging
      run: |
        echo "Deployment would happen here"
        # Add your deployment logic here 